version: "3.9"
services:
  webapp:
    image: infracloudio/csvserver:latest
    ports:
    - 9393:9300
    volumes:
    - inputFile:/csvserver/inputdata
    environment:
      CSVSERVER_BORDER: Orange
    command: ["/csvserver/csvserver"]
  prometheus:
    image: "prom/prometheus:v2.22.0"
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: /root/solution/prometheus.yml 
        target: /etc/prometheus/prometheus.yml
    depends_on:
    - webapp
